
	
MY_ADDRESS = 'teambreatheoffreshair@gmail.com'
PASSWORD = 'CIS467BFA'
ACCESS_KEY = 'AKIAIJ55NBMNXJBAX2MA'
SECRET_KEY = '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'
VAPID_PUBLIC_KEY = 'BCoTEua7v7fe1RBx_TQXkMgE-tumy5dYtff_49w0YcjXE1YNIAFK5R9_gV2TnNI2Ds3zZf0BrNgRGrmTTSHkTJU'
VAPID_PRIVATE_KEY = 'L7gNUcLcuQAddwwc2t_u9LIRo6MwDACJEYFnPYctfR0'
VAPID_ADMIN_EMAIL = 'teambreatheoffreshair@gmail.com'



